const data = {
  products: [
    {
      _id: "1",
      name: "Unique notes first year",
      category: "course books",
      image: "../images/1.png",
      publisher: "unique",
      countInStock: 12,
      price: 400,
      rating: 3.9,
      numReviews: 200,
      description: "this is according to latest syllabus use in all boards",
    },
    {
      _id: "2",
      name: "Federal notes first year",
      category: "course books",
      image: "../images/1.png",
      publisher: "unique",
      price: 800,
      countInStock: 0,
      rating: 3.1,
      numReviews: 120,
      description: "this is according to latest syllabus use in all boards",
    },
    {
      _id: "3",
      name: "Bll pen",
      category: "stationary",
      image: "../images/1.png",
      publisher: "piano",
      price: 60,
      countInStock: 100,
      rating: 4.9,
      numReviews: 70,
      description: "this is according to latest syllabus use in all boards",
    },
    {
      _id: "4",
      name: "Board Markers",
      category: "stationary",
      image: "../images/1.png",
      publisher: "piano",
      price: 120,
      countInStock: 512,
      rating: 2.9,
      numReviews: 160,
      description: "this is according very good",
    },
    {
      _id: "5",
      name: "Unique notes second year",
      category: "course books",
      image: "../images/1.png",
      publisher: "unique",
      price: 600,
      countInStock: 26,
      rating: 3.4,
      numReviews: 19,
      description: "this is according to latest syllabus use in all boards",
    },
    {
      _id: "6",
      name: "Calculator ASX",
      category: "Stationary",
      image: "../images/1.png",
      publisher: "Calculator",
      price: 900,
      countInStock: 9,
      rating: 4.4,
      numReviews: 159,
      description: "this is according to latest syllabus use in all boards",
    },
  ],
};
export default data;
